package com.starWholesale.hb.entity;
// Generated Jun 29, 2016 11:50:09 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArCustId generated by hbm2java
 */
@Entity
@Table(name = "ar_cust", catalog = "cppractice")
public class ArCust implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5785659545L;
	private String custNo;
	private String nam;
	private String namUpr;
	private String fstNam;
	private String fstNamUpr;
	private String lstNam;
	private String lstNamUpr;
	private String salutation;
	private String custTyp;
	private String adrs1;
	private String adrs2;
	private String adrs3;
	private String city;
	private String state;
	private String zipCod;
	private String cntry;
	private String phone1;
	private String phone2;
	private String mblPhone1;
	private String mblPhone2;
	private String fax1;
	private String fax2;
	private String contct1;
	private String contct2;
	private String emailAdrs1;
	private String emailAdrs2;

	
	@Id
	@Column(name = "CUST_NO", nullable = false, length = 15)
	public String getCustNo() {
		return this.custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	@Column(name = "NAM", nullable = false, length = 40)
	public String getNam() {
		return this.nam;
	}

	public void setNam(String nam) {
		this.nam = nam;
	}

	@Column(name = "NAM_UPR", length = 40)
	public String getNamUpr() {
		return this.namUpr;
	}

	public void setNamUpr(String namUpr) {
		this.namUpr = namUpr;
	}

	@Column(name = "FST_NAM", length = 15)
	public String getFstNam() {
		return this.fstNam;
	}

	public void setFstNam(String fstNam) {
		this.fstNam = fstNam;
	}

	@Column(name = "FST_NAM_UPR", length = 15)
	public String getFstNamUpr() {
		return this.fstNamUpr;
	}

	public void setFstNamUpr(String fstNamUpr) {
		this.fstNamUpr = fstNamUpr;
	}

	@Column(name = "LST_NAM", length = 25)
	public String getLstNam() {
		return this.lstNam;
	}

	public void setLstNam(String lstNam) {
		this.lstNam = lstNam;
	}

	@Column(name = "LST_NAM_UPR", length = 25)
	public String getLstNamUpr() {
		return this.lstNamUpr;
	}

	public void setLstNamUpr(String lstNamUpr) {
		this.lstNamUpr = lstNamUpr;
	}

	@Column(name = "SALUTATION", length = 10)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "CUST_TYP", nullable = false, length = 1)
	public String getCustTyp() {
		return this.custTyp;
	}

	public void setCustTyp(String custTyp) {
		this.custTyp = custTyp;
	}

	@Column(name = "ADRS_1", length = 40)
	public String getAdrs1() {
		return this.adrs1;
	}

	public void setAdrs1(String adrs1) {
		this.adrs1 = adrs1;
	}

	@Column(name = "ADRS_2", length = 40)
	public String getAdrs2() {
		return this.adrs2;
	}

	public void setAdrs2(String adrs2) {
		this.adrs2 = adrs2;
	}

	@Column(name = "ADRS_3", length = 40)
	public String getAdrs3() {
		return this.adrs3;
	}

	public void setAdrs3(String adrs3) {
		this.adrs3 = adrs3;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 10)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP_COD", length = 15)
	public String getZipCod() {
		return this.zipCod;
	}

	public void setZipCod(String zipCod) {
		this.zipCod = zipCod;
	}

	@Column(name = "CNTRY", length = 20)
	public String getCntry() {
		return this.cntry;
	}

	public void setCntry(String cntry) {
		this.cntry = cntry;
	}

	@Column(name = "PHONE_1", length = 25)
	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	@Column(name = "PHONE_2", length = 25)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "MBL_PHONE_1", length = 25)
	public String getMblPhone1() {
		return this.mblPhone1;
	}

	public void setMblPhone1(String mblPhone1) {
		this.mblPhone1 = mblPhone1;
	}

	@Column(name = "MBL_PHONE_2", length = 25)
	public String getMblPhone2() {
		return this.mblPhone2;
	}

	public void setMblPhone2(String mblPhone2) {
		this.mblPhone2 = mblPhone2;
	}

	@Column(name = "FAX_1", length = 25)
	public String getFax1() {
		return this.fax1;
	}

	public void setFax1(String fax1) {
		this.fax1 = fax1;
	}

	@Column(name = "FAX_2", length = 25)
	public String getFax2() {
		return this.fax2;
	}

	public void setFax2(String fax2) {
		this.fax2 = fax2;
	}

	@Column(name = "CONTCT_1", length = 40)
	public String getContct1() {
		return this.contct1;
	}

	public void setContct1(String contct1) {
		this.contct1 = contct1;
	}

	@Column(name = "CONTCT_2", length = 40)
	public String getContct2() {
		return this.contct2;
	}

	public void setContct2(String contct2) {
		this.contct2 = contct2;
	}

	@Column(name = "EMAIL_ADRS_1", length = 50)
	public String getEmailAdrs1() {
		return this.emailAdrs1;
	}

	public void setEmailAdrs1(String emailAdrs1) {
		this.emailAdrs1 = emailAdrs1;
	}

	@Column(name = "EMAIL_ADRS_2", length = 50)
	public String getEmailAdrs2() {
		return this.emailAdrs2;
	}

	public void setEmailAdrs2(String emailAdrs2) {
		this.emailAdrs2 = emailAdrs2;
	}


}
