package com.starWholesale.hb.entity;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartDetail generated by hbm2java
 */
@Entity
@Table(name = "cart_detail", catalog = "StarWholesale")
public class CartDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 19875425L;
	@Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "cart_detail_id", unique = true, nullable = false)
	private int cartDetailId;
/*	@Column(name = "cart_id", nullable = false)
	private int cartId;
*/	@Column(name = "p_id", nullable = false)
	private String PId;
	@Column(name = "qty", nullable = false)
	private int qty;
	@Column(name = "price", nullable = false)
	private int price;
	@Column(name = "status", nullable = false)
	private int status;


	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name="cart_id")
	private CartMaster cart;
	
	public CartMaster getCart() {
		return cart;
	}

	public void setCart(CartMaster cart) {
		this.cart = cart;
	}

	public CartDetail() {
	}

	public CartDetail(int cartDetailId, int cartId, String PId, int qty, int price, int status) {
		this.cartDetailId = cartDetailId;
	//	this.cartId = cartId;
		this.PId = PId;
		this.qty = qty;
		this.price = price;
		this.status = status;
	}

	public int getCartDetailId() {
		return this.cartDetailId;
	}

	public void setCartDetailId(int cartDetailId) {
		this.cartDetailId = cartDetailId;
	}
/*
	public int getCartId() {
		return this.cartId;
	}

	public void setCartId(int cartId) {
		this.cartId = cartId;
	}
*/
	public String getPId() {
		return this.PId;
	}

	public void setPId(String PId) {
		this.PId = PId;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
