package com.starWholesale.hb.entity;
// Generated Jun 25, 2016 2:51:05 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeviceTokenMaster generated by hbm2java
 */
@Entity
@Table(name = "device_token_master", catalog = "StarWholesale")
public class DeviceTokenMaster implements java.io.Serializable {

	@Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int deviceId;
	private int userId;
	private String token;
	private String deviceType;
	private int sstatus;
	private Date createdDate;
	private Date updatedDate;

	public DeviceTokenMaster() {
	}

	public DeviceTokenMaster(int deviceId, int userId, String token, String deviceType, int sstatus, Date createdDate,
			Date updatedDate) {
		this.deviceId = deviceId;
		this.userId = userId;
		this.token = token;
		this.deviceType = deviceType;
		this.sstatus = sstatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "device_id", unique = true, nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "token", length = 50)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "device_type", length = 50)
	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "sstatus")
	public int getSstatus() {
		return this.sstatus;
	}

	public void setSstatus(int sstatus) {
		this.sstatus = sstatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
