package com.starWholesale.hb.entity;
// Generated Jun 29, 2016 11:50:09 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.List;
import java.util.Set;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImCategCodId generated by hbm2java
 */
@Entity
@Table(name = "im_categ_cod", catalog = "cppractice")
public class ImCategCod implements java.io.Serializable {

	private static final long serialVersionUID = -7788619177798333712L;

	@Id
	@Column(name = "CATEG_COD", nullable = false, length = 10)
	private String categCod;
	@Column(name = "DESCR", nullable = false, length = 30)
	private String descr;
	@Column(name = "DESCR_UPR", length = 30)
	private String descrUpr;
	@Column(name = "PFT_CTR", length = 20)
	private String pftCtr;
	@Column(name = "MIN_PFT_PCT", precision = 9, scale = 3)
	private BigDecimal minPftPct;
	
	@Access(AccessType.PROPERTY)
	@OneToMany(targetEntity=ImItem.class, fetch = FetchType.EAGER,mappedBy="cat",cascade=CascadeType.ALL)
	private List<ImItem> imItem;
	
	
	public List<ImItem> getImItem() {
		return imItem ;
	}

	public void setImItem(List<ImItem> imItem) {
		this.imItem = imItem;
	}


	public String getCategCod() {
		return this.categCod;
	}

	public void setCategCod(String categCod) {
		this.categCod = categCod;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getDescrUpr() {
		return this.descrUpr;
	}

	public void setDescrUpr(String descrUpr) {
		this.descrUpr = descrUpr;
	}

	public String getPftCtr() {
		return this.pftCtr;
	}

	public void setPftCtr(String pftCtr) {
		this.pftCtr = pftCtr;
	}

	public BigDecimal getMinPftPct() {
		return this.minPftPct;
	}

	public void setMinPftPct(BigDecimal minPftPct) {
		this.minPftPct = minPftPct;
	}

}
