package com.starWholesale.hb.entity;
// Generated Jun 29, 2016 11:50:09 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * ImItemId generated by hbm2java
 */
@Entity
@Table(name = "im_item", catalog = "cppractice")
public class ImItem implements java.io.Serializable {

	@Id
	@Column(name = "ITEM_NO", nullable = false, length = 20)
	private String itemNo;
	@Column(name = "DESCR", nullable = false, length = 30)
	private String descr;
	@Column(name = "DESCR_UPR", length = 30)
	private String descrUpr;
	@Column(name = "LONG_DESCR", length = 50)
	private String longDescr;
	@Column(name = "LONG_DESCR_UPR", length = 50)
	private String longDescrUpr;
	@Column(name = "SHORT_DESCR", length = 15)
	private String shortDescr;

	@Column(name = "ITEM_TYP", nullable = false, length = 1)
	private String itemTyp;
	/*
	@Column(name = "CATEG_COD", length = 10)
	private String categCod;
	*/
	@Column(name = "SUBCAT_COD", length = 10)
	private String subcatCod;
	@Column(name = "QTY_DECS", nullable = false)
	private int qtyDecs;
	@Column(name = "PRC_DECS", nullable = false)
	private int prcDecs;
	@Column(name = "STK_UNIT", nullable = false, length = 15)
	private String stkUnit;
	@Column(name = "PRC_1", nullable = false, precision = 15, scale = 4)
	private BigDecimal prc1;
	@Column(name = "BARCOD", nullable = false, length = 20)
	private String barcod;

	@ElementCollection
	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name="CATEG_COD")
	private ImCategCod cat;
	
	public ImCategCod getCat() {
		return cat;
	}

	public void setCat(ImCategCod cat) {
		this.cat = cat;
	}

	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getDescrUpr() {
		return this.descrUpr;
	}

	public void setDescrUpr(String descrUpr) {
		this.descrUpr = descrUpr;
	}

	public String getLongDescr() {
		return this.longDescr;
	}

	public void setLongDescr(String longDescr) {
		this.longDescr = longDescr;
	}

	public String getLongDescrUpr() {
		return this.longDescrUpr;
	}

	public void setLongDescrUpr(String longDescrUpr) {
		this.longDescrUpr = longDescrUpr;
	}
	public String getShortDescr() {
		return this.shortDescr;
	}

	public void setShortDescr(String shortDescr) {
		this.shortDescr = shortDescr;
	}

	
	public String getItemTyp() {
		return this.itemTyp;
	}

	public void setItemTyp(String itemTyp) {
		this.itemTyp = itemTyp;
	}
/*
	public String getCategCod() {
		return this.categCod;
	}

	public void setCategCod(String categCod) {
		this.categCod = categCod;
	}
*/
	public String getSubcatCod() {
		return this.subcatCod;
	}

	public void setSubcatCod(String subcatCod) {
		this.subcatCod = subcatCod;
	}
	public int getQtyDecs() {
		return this.qtyDecs;
	}

	public void setQtyDecs(int qtyDecs) {
		this.qtyDecs = qtyDecs;
	}

	public int getPrcDecs() {
		return this.prcDecs;
	}

	public void setPrcDecs(int prcDecs) {
		this.prcDecs = prcDecs;
	}

	public String getStkUnit() {
		return this.stkUnit;
	}

	public void setStkUnit(String stkUnit) {
		this.stkUnit = stkUnit;
	}
	
	public BigDecimal getPrc1() {
		return this.prc1;
	}

	public void setPrc1(BigDecimal prc1) {
		this.prc1 = prc1;
	}
	
	public String getBarcod() {
		return this.barcod;
	}

	public void setBarcod(String barcod) {
		this.barcod = barcod;
	}

	

}
