package com.starWholesale.hb.entity;
// Generated Jun 25, 2016 2:51:05 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductMaster generated by hbm2java
 */
@Entity
@Table(name = "im_item", catalog = "StarWholesale")
public class ProductMaster implements java.io.Serializable {

	@Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int PId;
	private String pname;
	private int catid;
	private String pdetail;
	private long price;
	private String imageId;
	private String barcodeid;
	private Date cratedDate;
	private Date updatedDate;
	private int status;

	public ProductMaster() {
	}

	public ProductMaster(int PId, String pname, int catid, String pdetail, long price, String imageId, String barcodeid,
			Date cratedDate, Date updatedDate, int status) {
		this.PId = PId;
		this.pname = pname;
		this.catid = catid;
		this.pdetail = pdetail;
		this.price = price;
		this.imageId = imageId;
		this.barcodeid = barcodeid;
		this.cratedDate = cratedDate;
		this.updatedDate = updatedDate;
		this.status = status;
	}

	@Id

	@Column(name = "p_id", unique = true, nullable = false)
	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	@Column(name = "pname", nullable = false, length = 50)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "catid", nullable = false)
	public int getCatid() {
		return this.catid;
	}

	public void setCatid(int catid) {
		this.catid = catid;
	}

	@Column(name = "pdetail", nullable = false, length = 1000)
	public String getPdetail() {
		return this.pdetail;
	}

	public void setPdetail(String pdetail) {
		this.pdetail = pdetail;
	}

	@Column(name = "price", nullable = false)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	@Column(name = "image_id", nullable = false, length = 15)
	public String getImageId() {
		return this.imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	@Column(name = "barcodeid", nullable = false, length = 50)
	public String getBarcodeid() {
		return this.barcodeid;
	}

	public void setBarcodeid(String barcodeid) {
		this.barcodeid = barcodeid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crated_date", nullable = false, length = 19)
	public Date getCratedDate() {
		return this.cratedDate;
	}

	public void setCratedDate(Date cratedDate) {
		this.cratedDate = cratedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
