package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

/**
 * CartDetail generated by hbm2java
 */
public class CartDetail implements java.io.Serializable {

	private int cartDetailId;
	private int cartId;
	private String PId;
	private int qty;
	private int price;
	private int status;

	public CartDetail() {
	}

	public CartDetail(int cartDetailId, int cartId, String PId, int qty, int price, int status) {
		this.cartDetailId = cartDetailId;
		this.cartId = cartId;
		this.PId = PId;
		this.qty = qty;
		this.price = price;
		this.status = status;
	}

	public int getCartDetailId() {
		return this.cartDetailId;
	}

	public void setCartDetailId(int cartDetailId) {
		this.cartDetailId = cartDetailId;
	}

	public int getCartId() {
		return this.cartId;
	}

	public void setCartId(int cartId) {
		this.cartId = cartId;
	}

	public String getPId() {
		return this.PId;
	}

	public void setPId(String PId) {
		this.PId = PId;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
