package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.List;

/**
 * CartMaster generated by hbm2java
 */
public class CartMaster implements java.io.Serializable {

	private int cartId;
	private int userId;
	private Date createdDate;
	private Date updatedDate;
	private int status;
	private List<CartDetail> cartItems;

	public List<CartDetail> getCartItems() {
		return cartItems;
	}

	public void setCartItems(List<CartDetail> cartItems) {
		this.cartItems = cartItems;
	}

	public CartMaster() {
	}

	public CartMaster(int cartId, int userId, Date createdDate, Date updatedDate, int status) {
		this.cartId = cartId;
		this.userId = userId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.status = status;
	}

	public int getCartId() {
		return this.cartId;
	}

	public void setCartId(int cartId) {
		this.cartId = cartId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
