package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CategoryMaster generated by hbm2java
 */
public class CategoryMaster implements java.io.Serializable {

	private int categoryId;
	private String categoryName;
	private String categoryDetail;
	private Date createdDate;
	private Date updatedDate;
	private int status;

	public CategoryMaster() {
	}

	public CategoryMaster(int categoryId, String categoryName, String categoryDetail, Date createdDate,
			Date updatedDate, int status) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.categoryDetail = categoryDetail;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.status = status;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryDetail() {
		return this.categoryDetail;
	}

	public void setCategoryDetail(String categoryDetail) {
		this.categoryDetail = categoryDetail;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
