package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * DeviceTokenMaster generated by hbm2java
 */
public class DeviceTokenMaster implements java.io.Serializable {

	private int deviceId;
	private int userId;
	private String token;
	private String deviceType;
	private int sstatus;
	private Date createdDate;
	private Date updatedDate;

	public DeviceTokenMaster() {
	}

	public DeviceTokenMaster(int deviceId, int userId, String token, String deviceType, int sstatus, Date createdDate,
			Date updatedDate) {
		this.deviceId = deviceId;
		this.userId = userId;
		this.token = token;
		this.deviceType = deviceType;
		this.sstatus = sstatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public int getSstatus() {
		return this.sstatus;
	}

	public void setSstatus(int sstatus) {
		this.sstatus = sstatus;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
