package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.List;

/**
 * FlyerMaster generated by hbm2java
 */
public class FlyerMaster implements java.io.Serializable {

	private int flyerId;
	private int imageId;
	private String redirectionUrl;
	private String description;
	private Date createdDate;
	private Date updatedDate;
	private int status;
	private ImageMaster image; 
	
	public ImageMaster getImage() {
		return image;
	}

	public void setImage(ImageMaster image) {
		this.image = image;
	}

	public FlyerMaster() {
	}

	public FlyerMaster(int flyerId, int imageId, String redirectionUrl, String description, Date createdDate,
			Date updatedDate, int status) {
		this.flyerId = flyerId;
		this.imageId = imageId;
		this.redirectionUrl = redirectionUrl;
		this.description = description;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.status = status;
	}

	public int getFlyerId() {
		return this.flyerId;
	}

	public void setFlyerId(int flyerId) {
		this.flyerId = flyerId;
	}

	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	public String getRedirectionUrl() {
		return this.redirectionUrl;
	}

	public void setRedirectionUrl(String redirectionUrl) {
		this.redirectionUrl = redirectionUrl;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
