package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ImageMaster generated by hbm2java
 */
public class ImageMaster implements java.io.Serializable {

	private int imageId;
	private int imageType;
	private String imageUrl;
	private Date createdDate;
	private Date updatedDate;
	private int status;
	private String referenceId;

	public ImageMaster() {
	}

	public ImageMaster(int imageId, int imageType, String imageUrl, Date createdDate, Date updatedDate, int status,
			String referenceId) {
		this.imageId = imageId;
		this.imageType = imageType;
		this.imageUrl = imageUrl;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.status = status;
		this.referenceId = referenceId;
	}

	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	public int getImageType() {
		return this.imageType;
	}

	public void setImageType(int imageType) {
		this.imageType = imageType;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImageMaster))
			return false;
		ImageMaster castOther = (ImageMaster) other;

		return (this.getImageId() == castOther.getImageId()) && (this.getImageType() == castOther.getImageType())
				&& ((this.getImageUrl() == castOther.getImageUrl()) || (this.getImageUrl() != null
						&& castOther.getImageUrl() != null && this.getImageUrl().equals(castOther.getImageUrl())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate())
						|| (this.getCreatedDate() != null && castOther.getCreatedDate() != null
								&& this.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getUpdatedDate() == castOther.getUpdatedDate())
						|| (this.getUpdatedDate() != null && castOther.getUpdatedDate() != null
								&& this.getUpdatedDate().equals(castOther.getUpdatedDate())))
				&& (this.getStatus() == castOther.getStatus()) && (this.getReferenceId() == castOther.getReferenceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImageId();
		result = 37 * result + this.getImageType();
		result = 37 * result + (getImageUrl() == null ? 0 : this.getImageUrl().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getUpdatedDate() == null ? 0 : this.getUpdatedDate().hashCode());
		result = 37 * result + this.getStatus();
		result = 37 * result + (getReferenceId() == null ? 0 : this.getReferenceId().hashCode());
		return result;
	}

}
