package com.starWholesale.hb.dto;
// Generated Jun 30, 2016 1:01:41 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;



/**
 * ImCategCodId generated by hbm2java
 */
public class ImCategCod implements java.io.Serializable {

	private String categCod;
	private String descr;
	private String descrUpr;
	private String pftCtr;
	private BigDecimal minPftPct;
	

	private List<ImItem> products;


	public String getCategCod() {
		return categCod;
	}


	public void setCategCod(String categCod) {
		this.categCod = categCod;
	}


	public String getDescr() {
		return descr;
	}


	public void setDescr(String descr) {
		this.descr = descr;
	}


	public String getDescrUpr() {
		return descrUpr;
	}


	public void setDescrUpr(String descrUpr) {
		this.descrUpr = descrUpr;
	}


	public String getPftCtr() {
		return pftCtr;
	}


	public void setPftCtr(String pftCtr) {
		this.pftCtr = pftCtr;
	}


	public BigDecimal getMinPftPct() {
		return minPftPct;
	}


	public void setMinPftPct(BigDecimal minPftPct) {
		this.minPftPct = minPftPct;
	}


	public List<ImItem> getProducts() {
		return products;
	}


	public void setProducts(List<ImItem> products) {
		this.products = products;
	}
	
}
