package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ProductMaster generated by hbm2java
 */
public class ProductMaster implements java.io.Serializable {

	private int PId;
	private String pname;
	private int catid;
	private String pdetail;
	private long price;
	private String imageId;
	private String barcodeid;
	private Date cratedDate;
	private Date updatedDate;
	private int status;

	public ProductMaster() {
	}

	public ProductMaster(int PId, String pname, int catid, String pdetail, long price, String imageId, String barcodeid,
			Date cratedDate, Date updatedDate, int status) {
		this.PId = PId;
		this.pname = pname;
		this.catid = catid;
		this.pdetail = pdetail;
		this.price = price;
		this.imageId = imageId;
		this.barcodeid = barcodeid;
		this.cratedDate = cratedDate;
		this.updatedDate = updatedDate;
		this.status = status;
	}

	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public int getCatid() {
		return this.catid;
	}

	public void setCatid(int catid) {
		this.catid = catid;
	}

	public String getPdetail() {
		return this.pdetail;
	}

	public void setPdetail(String pdetail) {
		this.pdetail = pdetail;
	}

	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	public String getImageId() {
		return this.imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	public String getBarcodeid() {
		return this.barcodeid;
	}

	public void setBarcodeid(String barcodeid) {
		this.barcodeid = barcodeid;
	}

	public Date getCratedDate() {
		return this.cratedDate;
	}

	public void setCratedDate(Date cratedDate) {
		this.cratedDate = cratedDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
