package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RatingMaster generated by hbm2java
 */
public class RatingMaster implements java.io.Serializable {

	private int rateId;
	private int pid;
	private int userId;
	private int rate;
	private Date createdDate;
	private Date updatedDate;

	public RatingMaster() {
	}

	public RatingMaster(int rateId, int pid, int userId, int rate, Date createdDate, Date updatedDate) {
		this.rateId = rateId;
		this.pid = pid;
		this.userId = userId;
		this.rate = rate;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public int getRateId() {
		return this.rateId;
	}

	public void setRateId(int rateId) {
		this.rateId = rateId;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getRate() {
		return this.rate;
	}

	public void setRate(int rate) {
		this.rate = rate;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
