package com.starWholesale.hb.dto;
// Generated Jun 25, 2016 2:39:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * UserMaster generated by hbm2java
 */
public class UserMaster implements java.io.Serializable {

	private int userId;
	private String title;
	private String firstname;
	private String lastname;
	private String emailid;
	private String mobileno;
	private String password;
	private Date createdDate;
	private Date updatedDate;
	private int imageId;
	private int status;

	public UserMaster() {
	}

	public UserMaster(int userId, String title, String firstname, String lastname, String emailid, String mobileno,
			String password, Date createdDate, Date updatedDate, int imageId, int status) {
		this.userId = userId;
		this.title = title;
		this.firstname = firstname;
		this.lastname = lastname;
		this.emailid = emailid;
		this.mobileno = mobileno;
		this.password = password;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.imageId = imageId;
		this.status = status;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
